/**
 * English Language Pack
 */
export default {
  // Common
  common: {
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    confirm: 'Confirm',
    delete: 'Delete',
    reset: 'Reset',
    add: 'Add',
    edit: 'Edit',
    open: 'Open',
    yes: 'Yes',
    no: 'No',
    all: 'All',
    filter: 'Filter',
    search: 'Search',
    export: 'Export',
    clear: 'Clear',
    copy: 'Copy',
    copied: 'Copied',
    restore: 'Restore',
    restored: 'Restored',
    loading: 'Loading...',
    saving: 'Saving...',
    selectAll: 'Select All',
    selectNone: 'Select None',
    invertSelection: 'Invert',
    noData: 'No data',
  },

  // Header
  header: {
    settings: 'Settings',
    about: 'About',
    translationStatus: 'Translation Status',
    stopTranslation: 'Stop Translation',
    stopping: 'Stopping...',
    translating: 'Translating',
    progress: {
      items: 'Items {completed}/{total}, failed {failed}; Files {filesCompleted}/{filesTotal}',
      files: 'File Progress',
      entries: 'Entry Progress',
      currentFile: 'Current File',
      status: 'Status',
      unknownDir: '(Unknown directory)',
    },
    language: 'Language',
  },

  // Sidebar
  sidebar: {
    noProject: 'No project opened',
    directories: 'Directories',
    resourceFiles: 'Files',
    logs: 'Logs',
  },

  // Project actions
  project: {
    open: 'Open',
    close: 'Close',
    save: 'Save',
    opened: 'Project opened',
    openFailed: 'Failed to open project',
    closeFailed: 'Failed to close project',
    saved: 'Saved successfully',
    saveFailed: 'Failed to save',
    restoreDialog: {
      title: 'Restore Project',
      message: 'A previous project was detected. Would you like to restore it?',
      notice: 'Notice',
      noticeDesc:
        'Due to browser security restrictions, you need to reselect the project directory, but we can automatically restore the files you had open.',
      skip: 'Skip',
      restore: 'Restore Project',
    },
  },

  // Settings dialog
  settings: {
    title: 'Settings',
    description: 'Configure API, language order, and AI translation parameters',
    tabs: {
      general: 'General',
      language: 'Language',
      ai: 'AI',
    },
    general: {
      maxItemsPerRequest: 'Max items per batch',
      maxRetries: 'Max retries',
      requestTimeout: 'Request timeout (ms)',
      theme: 'Theme',
      themeLight: 'Light',
      themeDark: 'Dark',
      uiLanguage: 'UI Language',
    },
    language: {
      defaultLang: 'Default language',
      defaultLangSuffix: ' (always first)',
      enabledLanguages: 'Enabled languages',
      dragHint: 'Drag to reorder, click × to remove',
      noEnabledLanguages: 'No other languages enabled',
      availableLanguages: 'Available languages',
      addAll: 'Add all ({count})',
      clear: 'Clear',
      customLanguageManagement: 'Custom Language Management',
      customLanguageHint: 'Add any Android language code (e.g., th, vi, es)',
      addCustomLanguage: 'Add Custom Language',
      androidCode: 'Android Code',
      chineseName: 'Chinese Name',
      englishName: 'English Name',
      valuesDir: 'Values Directory',
      actions: 'Actions',
      addedCustomLanguages: 'Custom languages ({count})',
      noCustomLanguages: 'No custom languages',
      addLanguage: 'Add Language',
      androidCodePlaceholder: 'e.g., th, vi, es',
      chineseNamePlaceholder: 'e.g., Thai, Vietnamese',
      englishNamePlaceholder: 'e.g., Thai, Vietnamese',
    },
    ai: {
      apiConfig: 'API Configuration',
      apiUrl: 'API URL',
      apiUrlPlaceholder: 'https://api.openai.com/v1',
      apiKey: 'API Key',
      httpProxy: 'HTTP Proxy',
      proxyDisabledHint:
        'Proxy is disabled in browser environment. Please use browser proxy settings or extensions.',
      modelConfig: 'Model Configuration',
      modelName: 'Model Name',
      customModelName: 'Custom Model Name',
      customModelPlaceholder: 'gpt-4-turbo / claude-3-opus ...',
      testConnection: 'Test Connection',
      testing: 'Testing...',
      connectionSuccess: 'Connection successful',
      connectionFailed: 'Connection failed',
      promptConfig: 'Prompt Configuration',
      extraPrompt: 'Additional Prompt',
      extraPromptPlaceholder:
        'e.g., These texts are for an e-commerce app, please use shopping-related expressions.',
      singlePromptPreview: 'Single Translation Prompt Preview',
      batchPromptPreview: 'Batch Translation Prompt Preview',
      autoGenerated: 'Auto-generated',
      // Model descriptions
      modelDesc: {
        gpt5Mini: 'Recommended, balanced speed and quality',
        gpt5: 'Standard model, better results',
        gpt5Nano: 'Nano model, cost-effective',
        custom: 'Manually specify any model name (requires JSON mode support)',
      },
      // Prompt preview placeholders
      placeholder: {
        sourceLanguage: '[Source Language]',
        targetLanguage: '[Target Language]',
        resourceId: '[Resource ID]',
        originalText: '[Original Text]',
        optionalPrompt: '[Optional Prompt]',
      },
    },
    footer: {
      hint: 'Settings take effect immediately and are saved locally',
    },
    toast: {
      fillComplete: 'Please fill in all required fields',
      customLanguageAdded: 'Custom language added',
      customLanguageAddFailed: 'Failed to add custom language',
      customLanguageDeleted: 'Custom language deleted',
      customLanguageDeleteFailed: 'Failed to delete custom language',
      saved: 'Settings saved',
      saveFailed: 'Failed to save',
    },
  },

  // About dialog
  about: {
    title: 'About',
    tabs: {
      about: 'About',
      notice: 'Terms of Use',
    },
    version: 'Version {version}',
    techStack: 'Tech Stack',
    techStackContent: 'Vue 3 + Vite + Pinia + Element Plus + TypeScript',
    browserSupport: 'This tool supports Chrome/Edge and other modern browsers',
    copyright: 'Copyright © {year}',
    notice: {
      item1:
        'This is a pure frontend application. Except for accessing your configured OpenAI-compatible service, no data is sent to any other server.',
      item2:
        'Please configure the OpenAI-compatible API address and token before use, otherwise translation features will not work.',
      item3: 'No local files will be written until you click "Save".',
      item4:
        'The save operation will directly modify target files and cannot be undone. Please backup in advance.',
      item5:
        'Risk notice: Use this tool at your own risk. This project is not responsible for any consequences.',
    },
    acknowledge: 'I understand and continue',
  },

  // Workbench
  workbench: {
    selectXmlFile: 'Please select an XML file from the left panel',
    operations: {
      reloadFile: 'Reload File',
      batchTranslate: 'Batch Translate',
      projectTranslate: 'Project Translate',
      saveCurrentFile: 'Save Current File',
      searchPlaceholder: 'Search Key / Default text',
      filterAll: 'All',
      filterIncomplete: 'Incomplete',
      filterUntranslatable: 'Untranslatable',
      filterEdited: 'Edited',
      filtered: 'Filtered: {count}',
      selected: 'Selected: {count}',
    },
    table: {
      key: 'Key',
      translatable: 'Translatable',
      defaultText: 'Default Text',
    },
    menu: {
      translateItem: 'Translate this item...',
      restoreItem: 'Restore this item',
      translateLanguage: 'Translate this language...',
      restoreLanguage: 'Restore this language',
      quickTranslate: 'Quick Translate',
      translate: 'Translate...',
      restore: 'Restore',
      copyContent: 'Copy Content',
    },
    toast: {
      reloading: 'Reloading...',
      fileReloaded: 'File reloaded',
      reloadFailed: 'Failed to reload',
      fileSaved: 'File saved',
      openProjectFirst: 'Please open a project first',
      noTranslatableItems: 'No translatable items',
      noItemsToTranslate: 'No items to translate',
      batchTranslateComplete: 'Batch translation complete',
      projectTranslateComplete: 'Project translation complete',
      translateFailed: 'Translation failed',
      projectTranslateFailed: 'Project translation failed',
      restoreFailed: 'Failed to restore',
      selectTargetLanguage: 'Please select target languages',
    },
  },

  // Translate config dialog
  translateConfig: {
    title: 'Translation Config',
    pendingFiles: 'Pending Files',
    pendingItems: 'Pending Items',
    needLoadFile: ' (load files to calculate actual count)',
    selectRows: 'Select Rows',
    translateScope: 'Translation Scope',
    filter: 'Filter',
    filterLanguage: 'Filter Languages',
    selectedRows: 'Selected ({count} rows)',
    allRows: 'All ({count} rows)',
    currentDir: 'Current directory ({count} files)',
    allDirs: 'All ({count} files)',
    untranslated: 'Untranslated',
    untranslatedNeedLoad: 'Untranslated only (needs loading)',
    selectTargetLanguage: 'Select target languages ({selected}/{total})',
    startTranslate: 'Start Translation',
    translateItem: 'Translate Item',
    translateCell: 'Translate Cell',
    targetLanguage: 'Target Language',
  },

  // Array edit dialog
  arrayEdit: {
    title: 'Edit String Array',
    description:
      'Each line represents an array item. Saving will overwrite the entire array for this language.',
    placeholder: 'One array element per line',
  },

  // Resource tree
  resourceTree: {
    noProject: 'No project opened',
    expandAll: 'Expand All',
    collapseAll: 'Collapse All',
    filter: 'Filter',
  },

  // Log panel
  logs: {
    export: 'Export',
    clear: 'Clear',
  },

  // Language selector
  languageSelector: {
    title: 'Select target languages',
  },
}
